[mainframe_hosts]
Development = "devplex.example.com"
Production = "prdplex.example.com"
Testing = "testplex.example.com"

[security]
session_timeout_minutes = 30
max_login_attempts = 3
lockout_duration_minutes = 15

[certificates]
default_cert_path = "/path/to/cert"

[logging]
level = "INFO"
log_retention_days = 7 